version: "3.5"
services:
  dump:
    build:
      context: .
      dockerfile: Dockerfile.dump
    environment:
      PGDATABASE: ${DUMP_DATABASE}
      PGHOST: ${DUMP_PGHOST}
      PGPORT: ${DUMP_PGPORT}
      PGUSER: ${DUMP_PGUSER}
      PGPASSWORD: ${DUMP_PGPASSWORD}
      PGSCHEMA: ${DUMP_PGSCHEMA}
      DUMPFILE: ${DUMPFILE:-${TABLENAME}.dump}
      TABLENAME: ${TABLENAME}
    volumes:
      - ./tmp:/tmp
  restore:
    build:
      context: .
      dockerfile: Dockerfile.restore
    environment:
      PGDATABASE: ${RESTORE_DATABASE}
      PGHOST: ${RESTORE_PGHOST}
      PGPORT: ${RESTORE_PGPORT}
      PGUSER: ${RESTORE_PGUSER}
      PGPASSWORD: ${RESTORE_PGPASSWORD}
      PGSCHEMA: ${RESTORE_PGSCHEMA}
      DUMPFILE: ${DUMPFILE:-${TABLENAME}.dump}
      TABLENAME: ${TABLENAME}
    volumes:
      - ./tmp:/tmp
    networks:
      - oip_local

networks:
  oip_local:
    driver: bridge
    name: oip_local
